MathieuHeynen/CIRCLE

- Gemfile
- Gemfile.lock
- app/models/item.rb
- app/models/rental.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20240528104339_devise_create_users.rb
- db/migrate/20240528105704_create_items.rb
- db/migrate/20240528105941_create_rentals.rb
- db/schema.rb
- test/models/item_test.rb
- test/models/rental_test.rb
- test/models/user_test.rb
just created the devise to create users
-> missing the username input
3 models where created : Item, User, Rental
> First step of devise + generated the 3 models

- app/controllers/items_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/rentals_controller.rb
- app/views/pages/home.html.erb
- test/controllers/items_controller_test.rb
- test/controllers/rentals_controller_test.rb
We generated the items controller and rentals controllers and the folders in the views ✌️
> Created the items controller and the rentals controller

- app/controllers/application_controller.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
added the username input to the devise
> Added a username input to the devise

- config/routes.rb
creating the routes for the rental part. 
Only the create and show(for show, only if we had time to do it)
> creating the routes show and create for the rental

- app/views/shared/_navbar.html.erb
- added container to navbar so it aligns with the body container
- removed padding left and right
> aligned navbar with the banner

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- change body font
- changed background to white 
- updated container in navbar
> styling changes

- app/views/items/show.html.erb
- db/seeds.rb
made the show page with
- div for image (still to be changed to dynamic image picture the user uploads once cloudinary is set up)
- div for name, brand etc
> made the show page

- .gitignore
- Gemfile
- Gemfile.lock
- app/models/item.rb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20240529102521_create_active_storage_tables.active_storage.rb
- db/migrate/20240529103716_add_description_to_item.rb
- db/schema.rb
cloudinary inputs + description in item
> Modify item model

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/items/show.html.erb
> added button on show page

- app/controllers/application_controller.rb
- app/controllers/items_controller.rb
- app/views/items/show.html.erb
- deleted the touch file
- added the skip_before_action
- changed the modal so you can only rent when logged in
> authentification tweaks

- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- db/seeds.rb
> Aligned cards in index page

- app/assets/stylesheets/pages/_home.scss
- app/views/items/index.html.erb
> added card clickable

- app/views/items/_form.html.erb
repared the button of add cloths
> repared the new page

- app/assets/stylesheets/pages/_all_pages.scss
- app/controllers/pages_controller.rb
- app/views/pages/_form.html.erb
- app/views/pages/about_us.html.erb
- app/views/pages/contact_us.html.erb
- app/views/pages/terms_of_services.html.erb
- app/views/shared/_footer.html.erb
- config/routes.rb
Huge update on the footer, all the links and the contact form is done. Still need to work on the about us
> upgraded all the links of the footer and the pages linked to them

- app/models/rental.rb
- app/views/dashboard/show.html.erb
> tweaks on dashboard

- db/seeds.rb
> seeded some users and items

- app/controllers/rentals_controller.rb
- app/views/dashboard/show.html.erb
- added redirect to my dashboard when renting an item 
- added total amount to my rental in the dashboard
> finished redirect from rental to dashboard

- app/assets/stylesheets/pages/_all_pages.scss
- app/views/items/index.html.erb
> reparing the issue of the clickable banner

- app/controllers/items_controller.rb
updates items controller index action to Item.all.order(created_at: :desc)
> fixed so newly uploaded item gets push to the top of the list

- app/views/items/show.html.erb
added logic to item show page so user can't rent their own item
> fixed so user cant rent their own item

- app/controllers/rentals_controller.rb
- app/javascript/controllers/datepicker_controller.js
minimum today date for start date
> added the today date as the minimum date for the rent

- app/views/dashboard/show.html.erb
- app/views/items/show.html.erb
- added edit and delete functionality to the item show page
- added links to show page from dashboard when clicking on name and image
> added more edit and delete functionalities

- app/views/items/index.html.erb
- app/views/shared/_navbar.html.erb
- index page: changed Products to All Products
- dropdown navbar: change Lend item to Upload item
> small tweaks

- app/controllers/items_controller.rb
- app/views/shared/_navbar.html.erb
> search bar done
